project:
  type: book
  output-dir: docs

execute:
  freeze: auto

book:
  title: "Modelado Ordenado con R"
  reader-mode: true

  page-footer:
    left: |
      Modelado Ordenado con R fue escrito por Max Kuhn, y Julia Silge.
    right: |
      Este libro fue creado usando <a href="https://quarto.org/">Quarto</a>.
  cover-image: images/cover.png
  favicon: images/cover.png
  
  author: 
    - name: Max Kuhn
    - name: y
    - name: Julia Silge
  search: true
  sidebar: 
    pinned: true
    tools: 
      - icon: github
        menu: 
          - text: Original
            url: https://github.com/tidymodels/TMwR
          - text: Traducción
            url: https://github.com/davidrsch/TMwRes
  page-navigation: true
  chapters:
    - index.qmd

    - part: "INTRODUCCIÓN"
      chapters:
        - 01-software-modeling.qmd
        - 02-tidyverse.qmd
        - 03-base-r.qmd

    - part: "FUNDAMENTOS DE MODELADO"
      chapters:
        - 04-ames.qmd
        - 05-data-spending.qmd
        - 06-fitting-models.qmd
        - 07-the-model-workflow.qmd
        - 08-feature-engineering.qmd
        - 09-judging-model-effectiveness.qmd

    - part: "HERRAMIENTAS PARA CREAR MODELOS EFECTIVOS"
      chapters:
        - 10-resampling.qmd
        - 11-comparing-models.qmd
        - 12-tuning-parameters.qmd
        - 13-grid-search.qmd
        - 14-iterative-search.qmd
        - 15-workflow-sets.qmd
        
    - part: "MAS ALLÁ DE LO BÁSICO"
      chapters:
        - 16-dimensionality-reduction.qmd
        - 17-encoding-categorical-data.qmd
        - 18-explaining-models-and-predictions.qmd
        - 19-when-should-you-trust-predictions.qmd
        - 20-ensemble-models.qmd
        - 21-inferential-analysis.qmd
    
  appendices:
    - pre-proc-table.qmd
    - references.qmd

bibliography: TMwR.bib
lang: es

format:
  html:
    css: [style.css, TMwR.css]
    code-link: true
    cache: true
    author-meta: "Max Kuhn, y Julia Silge"
    callout-appearance: simple
    include-after-body: [ddrsch_script.html]

editor: visual

