<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="author" content="Max Kuhn, y Julia Silge">
<title>Modelado Ordenado con R - 17&nbsp; Encoding Categorical Data</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./18-explaining-models-and-predictions.html" rel="next">
<link href="./16-dimensionality-reduction.html" rel="prev">
<link href="./images/cover.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script src="site_libs/kePrint-0.0.1/kePrint.js"></script><link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<link rel="stylesheet" href="style.css">
<link rel="stylesheet" href="TMwR.css">
</head>
<body class="nav-sidebar floating">


<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./16-dimensionality-reduction.html">BEYOND THE BASICS</a></li><li class="breadcrumb-item"><a href="./17-encoding-categorical-data.html"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Encoding Categorical Data</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Modelado Ordenado con R</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/davidrsch/TMwRes" rel="" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Hello World</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">INTRODUCTION</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-software-modeling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Software for modeling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-tidyverse.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">A Tidyverse Primer</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-base-r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">A Review of R Modeling Fundamentals</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">MODELING BASICS</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-ames.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">The Ames Housing Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-data-spending.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Spending our Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-fitting-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Fitting Models with parsnip</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-the-model-workflow.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">A Model Workflow</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-feature-engineering.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Feature Engineering with recipes</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-judging-model-effectiveness.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Judging Model Effectiveness</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
 <span class="menu-text">TOOLS FOR CREATING EFFECTIVE MODELS</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-resampling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Resampling for Evaluating Performance</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-comparing-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Comparing Models with Resampling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-tuning-parameters.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Model Tuning and the Dangers of Overfitting</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-grid-search.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Grid Search</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-iterative-search.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Iterative Search</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-workflow-sets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Screening Many Models</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
 <span class="menu-text">BEYOND THE BASICS</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16-dimensionality-reduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Dimensionality Reduction</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./17-encoding-categorical-data.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Encoding Categorical Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./18-explaining-models-and-predictions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Explaining Models and Predictions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./19-when-should-you-trust-predictions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">When Should You Trust Your Predictions?</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./20-ensemble-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Ensembles of Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./21-inferential-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Inferential Analysis</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./pre-proc-table.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Recommended Preprocessing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li><a href="#is-an-encoding-necessary" id="toc-is-an-encoding-necessary" class="nav-link active" data-scroll-target="#is-an-encoding-necessary"><span class="header-section-number">17.1</span> Is an Encoding Necessary?</a></li>
  <li><a href="#encoding-ordinal-predictors" id="toc-encoding-ordinal-predictors" class="nav-link" data-scroll-target="#encoding-ordinal-predictors"><span class="header-section-number">17.2</span> Encoding Ordinal Predictors</a></li>
  <li>
<a href="#using-the-outcome-for-encoding-predictors" id="toc-using-the-outcome-for-encoding-predictors" class="nav-link" data-scroll-target="#using-the-outcome-for-encoding-predictors"><span class="header-section-number">17.3</span> Using the Outcome for Encoding Predictors</a>
  <ul class="collapse">
<li><a href="#effect-encodings-with-partial-pooling" id="toc-effect-encodings-with-partial-pooling" class="nav-link" data-scroll-target="#effect-encodings-with-partial-pooling"><span class="header-section-number">17.3.1</span> Effect encodings with partial pooling</a></li>
  </ul>
</li>
  <li><a href="#feature-hashing" id="toc-feature-hashing" class="nav-link" data-scroll-target="#feature-hashing"><span class="header-section-number">17.4</span> Feature Hashing</a></li>
  <li><a href="#more-encoding-options" id="toc-more-encoding-options" class="nav-link" data-scroll-target="#more-encoding-options"><span class="header-section-number">17.5</span> More Encoding Options</a></li>
  <li><a href="#sec-categorical-summary" id="toc-sec-categorical-summary" class="nav-link" data-scroll-target="#sec-categorical-summary"><span class="header-section-number">17.6</span> Chapter Summary</a></li>
  </ul><div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/davidrsch/TMwRes/edit/main/17-encoding-categorical-data.qmd" class="toc-action">Edit this page</a></p><p><a href="https://github.com/davidrsch/TMwRes/issues/new" class="toc-action">Report an issue</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title"><span id="sec-categorical" class="quarto-section-identifier"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Encoding Categorical Data</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header><p>For statistical modeling in R, the preferred representation for categorical or nominal data is a <em>factor</em>, which is a variable that can take on a limited number of different values; internally, factors are stored as a vector of integer values together with a set of text labels.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> In <a href="08-feature-engineering.html#sec-dummies"><span>Section&nbsp;8.4.1</span></a> we introduced feature engineering approaches to encode or transform qualitative or nominal data into a representation better suited for most model algorithms. We discussed how to transform a categorical variable, such as the <code>Bldg_Type</code> in our Ames housing data (with levels <code>OneFam</code>, <code>TwoFmCon</code>, <code>Duplex</code>, <code>Twnhs</code>, and <code>TwnhsE</code>), to a set of dummy or indicator variables like those shown in <a href="#tbl-encoding-dummies">Table&nbsp;<span>17.1</span></a>.</p>
<div class="cell" data-layout-align="center" data-hash="17-encoding-categorical-data_cache/html/tbl-encoding-dummies_44fffa16e97e776a292063c5b912ed4c">
<div class="cell-output-display">
<div id="tbl-encoding-dummies" class="anchored">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Table&nbsp;17.1: Dummy or indicator variable encodings for the building type predictor in the Ames training set.</caption>
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Raw Data</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">TwoFmCon</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Duplex</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Twnhs</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">TwnhsE</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">OneFam</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">TwoFmCon</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Duplex</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Twnhs</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">TwnhsE</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
<p>Many model implementations require such a transformation to a numeric representation for categorical data.</p>
<div class="rmdnote">
<p><a href="pre-proc-table.html">Appendix&nbsp;<span>A</span></a> presents a table of recommended preprocessing techniques for different models; notice how many of the models in the table require a numeric encoding for all predictors.</p>
</div>
<p>However, for some realistic data sets, straightforward dummy variables are not a good fit. This often happens because there are <em>too many</em> categories or there are <em>new</em> categories at prediction time. In this chapter, we discuss more sophisticated options for encoding categorical predictors that address these issues. These options are available as tidymodels recipe steps in the <a href="https://embed.tidymodels.org/"><span class="pkg">embed</span></a> and <a href="https://textrecipes.tidymodels.org/"><span class="pkg">textrecipes</span></a> packages.</p>
<section id="is-an-encoding-necessary" class="level2" data-number="17.1"><h2 data-number="17.1" class="anchored" data-anchor-id="is-an-encoding-necessary">
<span class="header-section-number">17.1</span> Is an Encoding Necessary?</h2>
<p>A minority of models, such as those based on trees or rules, can handle categorical data natively and do not require encoding or transformation of these kinds of features. A tree-based model can natively partition a variable like <code>Bldg_Type</code> into groups of factor levels, perhaps <code>OneFam</code> alone in one group and <code>Duplex</code> and <code>Twnhs</code> together in another group. Naive Bayes models are another example where the structure of the model can deal with categorical variables natively; distributions are computed within each level, for example, for all the different kinds of <code>Bldg_Type</code> in the data set.</p>
<p>These models that can handle categorical features natively can <em>also</em> deal with numeric, continuous features, making the transformation or encoding of such variables optional. Does this help in some way, perhaps with model performance or time to train models? Typically no, as Section 5.7 of <span class="citation" data-cites="fes">Kuhn and Johnson (<a href="references.html#ref-fes" role="doc-biblioref">2020</a>)</span> shows using benchmark data sets with untransformed factor variables compared with transformed dummy variables for those same features. In short, using dummy encodings did not typically result in better model performance but often required more time to train the models.</p>
<div class="rmdnote">
<p>We advise starting with untransformed categorical variables when a model allows it; note that more complex encodings often do not result in better performance for such models.</p>
</div>
</section><section id="encoding-ordinal-predictors" class="level2" data-number="17.2"><h2 data-number="17.2" class="anchored" data-anchor-id="encoding-ordinal-predictors">
<span class="header-section-number">17.2</span> Encoding Ordinal Predictors</h2>
<p>Sometimes qualitative columns can be <em>ordered</em>, such as “low,” “medium,” and “high”. In base R, the default encoding strategy is to make new numeric columns that are polynomial expansions of the data. For columns that have five ordinal values, like the example shown in <a href="#tbl-encoding-ordered-table">Table&nbsp;<span>17.2</span></a>, the factor column is replaced with columns for linear, quadratic, cubic, and quartic terms:</p>
<div class="cell" data-layout-align="center" data-hash="17-encoding-categorical-data_cache/html/tbl-encoding-ordered-table_57527f7c1634ee82c30f7303ee30bb4e">
<div class="cell-output-display">
<div id="tbl-encoding-ordered-table" class="anchored">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Table&nbsp;17.2: Polynominal expansions for encoding an ordered variable.</caption>
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Raw Data</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Linear</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Quadratic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Cubic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Quartic</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">none</td>
<td style="text-align: right;">-0.63</td>
<td style="text-align: right;">0.53</td>
<td style="text-align: right;">-0.32</td>
<td style="text-align: right;">0.12</td>
</tr>
<tr class="even">
<td style="text-align: left;">a little</td>
<td style="text-align: right;">-0.32</td>
<td style="text-align: right;">-0.27</td>
<td style="text-align: right;">0.63</td>
<td style="text-align: right;">-0.48</td>
</tr>
<tr class="odd">
<td style="text-align: left;">some</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">-0.53</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.72</td>
</tr>
<tr class="even">
<td style="text-align: left;">a bunch</td>
<td style="text-align: right;">0.32</td>
<td style="text-align: right;">-0.27</td>
<td style="text-align: right;">-0.63</td>
<td style="text-align: right;">-0.48</td>
</tr>
<tr class="odd">
<td style="text-align: left;">copious amounts</td>
<td style="text-align: right;">0.63</td>
<td style="text-align: right;">0.53</td>
<td style="text-align: right;">0.32</td>
<td style="text-align: right;">0.12</td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
<p>While this is not unreasonable, it is not an approach that people tend to find useful. For example, an 11-degree polynomial is probably not the most effective way of encoding an ordinal factor for the months of the year. Instead, consider trying recipe steps related to ordered factors, such as <code><a href="https://recipes.tidymodels.org/reference/step_unorder.html">step_unorder()</a></code>, to convert to regular factors, and <code><a href="https://recipes.tidymodels.org/reference/step_ordinalscore.html">step_ordinalscore()</a></code>, which maps specific numeric values to each factor level.</p>
</section><section id="using-the-outcome-for-encoding-predictors" class="level2" data-number="17.3"><h2 data-number="17.3" class="anchored" data-anchor-id="using-the-outcome-for-encoding-predictors">
<span class="header-section-number">17.3</span> Using the Outcome for Encoding Predictors</h2>
<p>There are multiple options for encodings more complex than dummy or indicator variables. One method called <em>effect</em> or <em>likelihood encodings</em> replaces the original categorical variables with a single numeric column that measures the effect of those data <span class="citation" data-cites="MicciBarreca2001 Zumel2019">(<a href="references.html#ref-MicciBarreca2001" role="doc-biblioref">Micci-Barreca 2001</a>; <a href="references.html#ref-Zumel2019" role="doc-biblioref">Zumel and Mount 2019</a>)</span>. For example, for the neighborhood predictor in the Ames housing data, we can compute the mean or median sale price for each neighborhood (as shown in <a href="#fig-encoding-mean-price">Figure&nbsp;<span>17.1</span></a>) and substitute these means for the original data values:</p>
<div class="cell" data-layout-align="center" data-hash="17-encoding-categorical-data_cache/html/fig-encoding-mean-price_7d0ed3f9c28313cfce22dd956ef38f9f">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">ames_train</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">group_by</span><span class="op">(</span><span class="va">Neighborhood</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">summarize</span><span class="op">(</span>mean <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">Sale_Price</span><span class="op">)</span>,</span>
<span>            std_err <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">Sale_Price</span><span class="op">)</span> <span class="op">/</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">Sale_Price</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">ggplot</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>y <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/reorder.factor.html">reorder</a></span><span class="op">(</span><span class="va">Neighborhood</span>, <span class="va">mean</span><span class="op">)</span>, x <span class="op">=</span> <span class="va">mean</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">geom_point</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_errorbar</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>xmin <span class="op">=</span> <span class="va">mean</span> <span class="op">-</span> <span class="fl">1.64</span> <span class="op">*</span> <span class="va">std_err</span>, xmax <span class="op">=</span> <span class="va">mean</span> <span class="op">+</span> <span class="fl">1.64</span> <span class="op">*</span> <span class="va">std_err</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span>y <span class="op">=</span> <span class="cn">NULL</span>, x <span class="op">=</span> <span class="st">"Price (mean, log scale)"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-encoding-mean-price" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="17-encoding-categorical-data_files/figure-html/fig-encoding-mean-price-1.png" class="img-fluid figure-img" alt="A chart with points and error bars for the mean home price for neighborhoods in the Ames training set. The most expensive neighborhoods are Northridge and Stone Brook, while the least expensive are Iowa DOT and Railroad and Meadow Village." width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;17.1: Mean home price for neighborhoods in the Ames training set, which can be used as an effect encoding for this categorical variable</figcaption></figure>
</div>
</div>
</div>
<p>This kind of effect encoding works well when your categorical variable has many levels. In tidymodels, the <span class="pkg">embed</span> package includes several recipe step functions for different kinds of effect encodings, such as <code><a href="https://embed.tidymodels.org/reference/step_lencode_glm.html">step_lencode_glm()</a></code>, <code><a href="https://embed.tidymodels.org/reference/step_lencode_mixed.html">step_lencode_mixed()</a></code>, and <code><a href="https://embed.tidymodels.org/reference/step_lencode_bayes.html">step_lencode_bayes()</a></code>. These steps use a generalized linear model to estimate the effect of each level in a categorical predictor on the outcome. When using a recipe step like <code><a href="https://embed.tidymodels.org/reference/step_lencode_glm.html">step_lencode_glm()</a></code>, specify the variable being encoded first and then the outcome using <code>vars()</code>:</p>
<div class="cell" data-layout-align="center" data-hash="17-encoding-categorical-data_cache/html/unnamed-chunk-4_aea588047f8075dbb064335a4788d18d">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://embed.tidymodels.org">embed</a></span><span class="op">)</span></span>
<span></span>
<span><span class="va">ames_glm</span> <span class="op">&lt;-</span> </span>
<span>  <span class="fu"><a href="https://recipes.tidymodels.org/reference/recipe.html">recipe</a></span><span class="op">(</span><span class="va">Sale_Price</span> <span class="op">~</span> <span class="va">Neighborhood</span> <span class="op">+</span> <span class="va">Gr_Liv_Area</span> <span class="op">+</span> <span class="va">Year_Built</span> <span class="op">+</span> <span class="va">Bldg_Type</span> <span class="op">+</span> </span>
<span>           <span class="va">Latitude</span> <span class="op">+</span> <span class="va">Longitude</span>, data <span class="op">=</span> <span class="va">ames_train</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://recipes.tidymodels.org/reference/step_log.html">step_log</a></span><span class="op">(</span><span class="va">Gr_Liv_Area</span>, base <span class="op">=</span> <span class="fl">10</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://embed.tidymodels.org/reference/step_lencode_glm.html">step_lencode_glm</a></span><span class="op">(</span><span class="va">Neighborhood</span>, outcome <span class="op">=</span> <span class="fu">vars</span><span class="op">(</span><span class="va">Sale_Price</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://recipes.tidymodels.org/reference/step_dummy.html">step_dummy</a></span><span class="op">(</span><span class="fu"><a href="https://recipes.tidymodels.org/reference/has_role.html">all_nominal_predictors</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://recipes.tidymodels.org/reference/step_interact.html">step_interact</a></span><span class="op">(</span> <span class="op">~</span> <span class="va">Gr_Liv_Area</span><span class="op">:</span><span class="fu">starts_with</span><span class="op">(</span><span class="st">"Bldg_Type_"</span><span class="op">)</span> <span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://recipes.tidymodels.org/reference/step_ns.html">step_ns</a></span><span class="op">(</span><span class="va">Latitude</span>, <span class="va">Longitude</span>, deg_free <span class="op">=</span> <span class="fl">20</span><span class="op">)</span></span>
<span></span>
<span><span class="va">ames_glm</span></span>
<span><span class="co">## </span></span>
<span><span class="co">## ── Recipe ───────────────────────────────────────────────────────────────────────────</span></span>
<span><span class="co">## </span></span>
<span><span class="co">## ── Inputs</span></span>
<span><span class="co">## Number of variables by role</span></span>
<span><span class="co">## outcome:   1</span></span>
<span><span class="co">## predictor: 6</span></span>
<span><span class="co">## </span></span>
<span><span class="co">## ── Operations</span></span>
<span><span class="co">## • Log transformation on: Gr_Liv_Area</span></span>
<span><span class="co">## • Linear embedding for factors via GLM for: Neighborhood</span></span>
<span><span class="co">## • Dummy variables from: all_nominal_predictors()</span></span>
<span><span class="co">## • Interactions with: Gr_Liv_Area:starts_with("Bldg_Type_")</span></span>
<span><span class="co">## • Natural splines on: Latitude, Longitude</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>As detailed in <a href="16-dimensionality-reduction.html#sec-recipe-functions"><span>Section&nbsp;16.4</span></a>, we can <code><a href="https://recipes.tidymodels.org/reference/prep.html">prep()</a></code> our recipe to fit or estimate parameters for the preprocessing transformations using training data. We can then <code><a href="https://generics.r-lib.org/reference/tidy.html">tidy()</a></code> this prepared recipe to see the results:</p>
<div class="cell" data-layout-align="center" data-hash="17-encoding-categorical-data_cache/html/unnamed-chunk-5_7b936810cddfe58ca47460c6bc9ced99">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">glm_estimates</span> <span class="op">&lt;-</span></span>
<span>  <span class="fu"><a href="https://recipes.tidymodels.org/reference/prep.html">prep</a></span><span class="op">(</span><span class="va">ames_glm</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://generics.r-lib.org/reference/tidy.html">tidy</a></span><span class="op">(</span>number <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></span>
<span></span>
<span><span class="va">glm_estimates</span></span>
<span><span class="co">## # A tibble: 29 × 4</span></span>
<span><span class="co">##   level              value terms        id               </span></span>
<span><span class="co">##   &lt;chr&gt;              &lt;dbl&gt; &lt;chr&gt;        &lt;chr&gt;            </span></span>
<span><span class="co">## 1 North_Ames          5.15 Neighborhood lencode_glm_ZsXdy</span></span>
<span><span class="co">## 2 College_Creek       5.29 Neighborhood lencode_glm_ZsXdy</span></span>
<span><span class="co">## 3 Old_Town            5.07 Neighborhood lencode_glm_ZsXdy</span></span>
<span><span class="co">## 4 Edwards             5.09 Neighborhood lencode_glm_ZsXdy</span></span>
<span><span class="co">## 5 Somerset            5.35 Neighborhood lencode_glm_ZsXdy</span></span>
<span><span class="co">## 6 Northridge_Heights  5.49 Neighborhood lencode_glm_ZsXdy</span></span>
<span><span class="co">## # ℹ 23 more rows</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>When we use the newly encoded <code>Neighborhood</code> numeric variable created via this method, we substitute the original level (such as <code>"North_Ames"</code>) with the estimate for <code>Sale_Price</code> from the GLM.</p>
<p>Effect encoding methods like this one can also seamlessly handle situations where a novel factor level is encountered in the data. This <code>value</code> is the predicted price from the GLM when we don’t have any specific neighborhood information:</p>
<div class="cell" data-layout-align="center" data-hash="17-encoding-categorical-data_cache/html/unnamed-chunk-6_ee062f5fb76c858022a02bbb6fb7a821">
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">glm_estimates</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">level</span> <span class="op">==</span> <span class="st">"..new"</span><span class="op">)</span></span>
<span><span class="co">## # A tibble: 1 × 4</span></span>
<span><span class="co">##   level value terms        id               </span></span>
<span><span class="co">##   &lt;chr&gt; &lt;dbl&gt; &lt;chr&gt;        &lt;chr&gt;            </span></span>
<span><span class="co">## 1 ..new  5.23 Neighborhood lencode_glm_ZsXdy</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="rmdwarn">
<p>Effect encodings can be powerful but should be used with care. The effects should be computed from the training set, after data splitting. This type of supervised preprocessing should be rigorously resampled to avoid overfitting (see <a href="10-resampling.html">Chapter&nbsp;<span>10</span></a>).</p>
</div>
<p>When you create an effect encoding for your categorical variable, you are effectively layering a mini-model inside your actual model. The possibility of overfitting with effect encodings is a representative example for why feature engineering <em>must</em> be considered part of the model process, as described in Chapter @ref(workflows), and why feature engineering must be estimated together with model parameters inside resampling.</p>
<section id="effect-encodings-with-partial-pooling" class="level3" data-number="17.3.1"><h3 data-number="17.3.1" class="anchored" data-anchor-id="effect-encodings-with-partial-pooling">
<span class="header-section-number">17.3.1</span> Effect encodings with partial pooling</h3>
<p>Creating an effect encoding with <code><a href="https://embed.tidymodels.org/reference/step_lencode_glm.html">step_lencode_glm()</a></code> estimates the effect separately for each factor level (in this example, neighborhood). However, some of these neighborhoods have many houses in them, and some have only a few. There is much more uncertainty in our measurement of price for the single training set home in the Landmark neighborhood than the 354 training set homes in North Ames. We can use <em>partial pooling</em> to adjust these estimates so that levels with small sample sizes are shrunken toward the overall mean. The effects for each level are modeled all at once using a mixed or hierarchical generalized linear model:</p>
<div class="cell" data-layout-align="center" data-hash="17-encoding-categorical-data_cache/html/unnamed-chunk-7_bb879ed03c9d916dda3b33e5cefc3ef5">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">ames_mixed</span> <span class="op">&lt;-</span> </span>
<span>  <span class="fu"><a href="https://recipes.tidymodels.org/reference/recipe.html">recipe</a></span><span class="op">(</span><span class="va">Sale_Price</span> <span class="op">~</span> <span class="va">Neighborhood</span> <span class="op">+</span> <span class="va">Gr_Liv_Area</span> <span class="op">+</span> <span class="va">Year_Built</span> <span class="op">+</span> <span class="va">Bldg_Type</span> <span class="op">+</span> </span>
<span>           <span class="va">Latitude</span> <span class="op">+</span> <span class="va">Longitude</span>, data <span class="op">=</span> <span class="va">ames_train</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://recipes.tidymodels.org/reference/step_log.html">step_log</a></span><span class="op">(</span><span class="va">Gr_Liv_Area</span>, base <span class="op">=</span> <span class="fl">10</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://embed.tidymodels.org/reference/step_lencode_mixed.html">step_lencode_mixed</a></span><span class="op">(</span><span class="va">Neighborhood</span>, outcome <span class="op">=</span> <span class="fu">vars</span><span class="op">(</span><span class="va">Sale_Price</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://recipes.tidymodels.org/reference/step_dummy.html">step_dummy</a></span><span class="op">(</span><span class="fu"><a href="https://recipes.tidymodels.org/reference/has_role.html">all_nominal_predictors</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://recipes.tidymodels.org/reference/step_interact.html">step_interact</a></span><span class="op">(</span> <span class="op">~</span> <span class="va">Gr_Liv_Area</span><span class="op">:</span><span class="fu">starts_with</span><span class="op">(</span><span class="st">"Bldg_Type_"</span><span class="op">)</span> <span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://recipes.tidymodels.org/reference/step_ns.html">step_ns</a></span><span class="op">(</span><span class="va">Latitude</span>, <span class="va">Longitude</span>, deg_free <span class="op">=</span> <span class="fl">20</span><span class="op">)</span></span>
<span></span>
<span><span class="va">ames_mixed</span></span>
<span><span class="co">## </span></span>
<span><span class="co">## ── Recipe ───────────────────────────────────────────────────────────────────────────</span></span>
<span><span class="co">## </span></span>
<span><span class="co">## ── Inputs</span></span>
<span><span class="co">## Number of variables by role</span></span>
<span><span class="co">## outcome:   1</span></span>
<span><span class="co">## predictor: 6</span></span>
<span><span class="co">## </span></span>
<span><span class="co">## ── Operations</span></span>
<span><span class="co">## • Log transformation on: Gr_Liv_Area</span></span>
<span><span class="co">## • Linear embedding for factors via mixed effects for: Neighborhood</span></span>
<span><span class="co">## • Dummy variables from: all_nominal_predictors()</span></span>
<span><span class="co">## • Interactions with: Gr_Liv_Area:starts_with("Bldg_Type_")</span></span>
<span><span class="co">## • Natural splines on: Latitude, Longitude</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s <code><a href="https://recipes.tidymodels.org/reference/prep.html">prep()</a></code> and <code><a href="https://generics.r-lib.org/reference/tidy.html">tidy()</a></code> this recipe to see the results:</p>
<div class="cell" data-layout-align="center" data-hash="17-encoding-categorical-data_cache/html/unnamed-chunk-8_28667e5f8b61c6779df2f2b5979ee58d">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">mixed_estimates</span> <span class="op">&lt;-</span></span>
<span>  <span class="fu"><a href="https://recipes.tidymodels.org/reference/prep.html">prep</a></span><span class="op">(</span><span class="va">ames_mixed</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://generics.r-lib.org/reference/tidy.html">tidy</a></span><span class="op">(</span>number <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></span>
<span></span>
<span><span class="va">mixed_estimates</span></span>
<span><span class="co">## # A tibble: 29 × 4</span></span>
<span><span class="co">##   level              value terms        id                 </span></span>
<span><span class="co">##   &lt;chr&gt;              &lt;dbl&gt; &lt;chr&gt;        &lt;chr&gt;              </span></span>
<span><span class="co">## 1 North_Ames          5.15 Neighborhood lencode_mixed_SC9hi</span></span>
<span><span class="co">## 2 College_Creek       5.29 Neighborhood lencode_mixed_SC9hi</span></span>
<span><span class="co">## 3 Old_Town            5.07 Neighborhood lencode_mixed_SC9hi</span></span>
<span><span class="co">## 4 Edwards             5.10 Neighborhood lencode_mixed_SC9hi</span></span>
<span><span class="co">## 5 Somerset            5.35 Neighborhood lencode_mixed_SC9hi</span></span>
<span><span class="co">## 6 Northridge_Heights  5.49 Neighborhood lencode_mixed_SC9hi</span></span>
<span><span class="co">## # ℹ 23 more rows</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>New levels are then encoded at close to the same value as with the GLM:</p>
<div class="cell" data-layout-align="center" data-hash="17-encoding-categorical-data_cache/html/unnamed-chunk-9_56f051a16e4be7ef9558a795a293f0e6">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">mixed_estimates</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">level</span> <span class="op">==</span> <span class="st">"..new"</span><span class="op">)</span></span>
<span><span class="co">## # A tibble: 1 × 4</span></span>
<span><span class="co">##   level value terms        id                 </span></span>
<span><span class="co">##   &lt;chr&gt; &lt;dbl&gt; &lt;chr&gt;        &lt;chr&gt;              </span></span>
<span><span class="co">## 1 ..new  5.23 Neighborhood lencode_mixed_SC9hi</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="rmdnote">
<p>You can use a fully Bayesian hierarchical model for the effects in the same way with <code><a href="https://embed.tidymodels.org/reference/step_lencode_bayes.html">step_lencode_bayes()</a></code>.</p>
</div>
<p>Let’s visually compare the effects using partial pooling vs.&nbsp;no pooling in <a href="#fig-encoding-compare-pooling">Figure&nbsp;<span>17.2</span></a>:</p>
<div class="cell" data-layout-align="center" data-hash="17-encoding-categorical-data_cache/html/fig-encoding-compare-pooling_ea97cff2c1cf1b09f823352078b205c1">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">glm_estimates</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu">rename</span><span class="op">(</span>`no pooling` <span class="op">=</span> <span class="va">value</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu">left_join</span><span class="op">(</span></span>
<span>    <span class="va">mixed_estimates</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>      <span class="fu">rename</span><span class="op">(</span>`partial pooling` <span class="op">=</span> <span class="va">value</span><span class="op">)</span>, by <span class="op">=</span> <span class="st">"level"</span></span>
<span>  <span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu">left_join</span><span class="op">(</span></span>
<span>    <span class="va">ames_train</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>      <span class="fu">count</span><span class="op">(</span><span class="va">Neighborhood</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>      <span class="fu">mutate</span><span class="op">(</span>level <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/character.html">as.character</a></span><span class="op">(</span><span class="va">Neighborhood</span><span class="op">)</span><span class="op">)</span></span>
<span>  <span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu">ggplot</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span><span class="va">`no pooling`</span>, <span class="va">`partial pooling`</span>, size <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="va">n</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_abline</span><span class="op">(</span>color <span class="op">=</span> <span class="st">"gray50"</span>, lty <span class="op">=</span> <span class="fl">2</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_point</span><span class="op">(</span>alpha <span class="op">=</span> <span class="fl">0.7</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">coord_fixed</span><span class="op">(</span><span class="op">)</span></span>
<span><span class="co">## Warning: Removed 1 rows containing missing values (`geom_point()`).</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-encoding-compare-pooling" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="17-encoding-categorical-data_files/figure-html/fig-encoding-compare-pooling-1.png" class="img-fluid figure-img" alt="A scatter chart comparing the effect encodings for neighborhood estimated without pooling to those with partial pooling. Almost all neighborhoods are very close to the slope = 1 line, but the neighborhoods with the fewest homes are further away." width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;17.2: Comparing the effect encodings for neighborhood estimated without pooling to those with partial pooling</figcaption></figure>
</div>
</div>
</div>
<p>Notice in <a href="#fig-encoding-compare-pooling">Figure&nbsp;<span>17.2</span></a> that most estimates for neighborhood effects are about the same when we compare pooling to no pooling. However, the neighborhoods with the fewest homes in them have been pulled (either up or down) toward the mean effect. When we use pooling, we shrink the effect estimates toward the mean because we don’t have as much evidence about the price in those neighborhoods.</p>
</section></section><section id="feature-hashing" class="level2" data-number="17.4"><h2 data-number="17.4" class="anchored" data-anchor-id="feature-hashing">
<span class="header-section-number">17.4</span> Feature Hashing</h2>
<p>Traditional dummy variables as described in <a href="08-feature-engineering.html#sec-dummies"><span>Section&nbsp;8.4.1</span></a> require that all of the possible categories be known to create a full set of numeric features. <em>Feature hashing</em> methods <span class="citation" data-cites="weinberger2009feature">(<a href="references.html#ref-weinberger2009feature" role="doc-biblioref">Weinberger et al. 2009</a>)</span> also create dummy variables, but only consider the value of the category to assign it to a predefined pool of dummy variables. Let’s look at the <code>Neighborhood</code> values in Ames again and use the <code><a href="https://rlang.r-lib.org/reference/hash.html">rlang::hash()</a></code> function to understand more:</p>
<div class="cell" data-layout-align="center" data-hash="17-encoding-categorical-data_cache/html/unnamed-chunk-11_31846aad72653a52e85a8740b90f37aa">
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://rlang.r-lib.org">rlang</a></span><span class="op">)</span></span>
<span></span>
<span><span class="va">ames_hashed</span> <span class="op">&lt;-</span></span>
<span>  <span class="va">ames_train</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu">mutate</span><span class="op">(</span>Hash <span class="op">=</span> <span class="fu">map_chr</span><span class="op">(</span><span class="va">Neighborhood</span>, <span class="va">hash</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">ames_hashed</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu">select</span><span class="op">(</span><span class="va">Neighborhood</span>, <span class="va">Hash</span><span class="op">)</span></span>
<span><span class="co">## # A tibble: 2,342 × 2</span></span>
<span><span class="co">##   Neighborhood    Hash                            </span></span>
<span><span class="co">##   &lt;fct&gt;           &lt;chr&gt;                           </span></span>
<span><span class="co">## 1 North_Ames      076543f71313e522efe157944169d919</span></span>
<span><span class="co">## 2 North_Ames      076543f71313e522efe157944169d919</span></span>
<span><span class="co">## 3 Briardale       b598bec306983e3e68a3118952df8cf0</span></span>
<span><span class="co">## 4 Briardale       b598bec306983e3e68a3118952df8cf0</span></span>
<span><span class="co">## 5 Northpark_Villa 6af95b5db968bf393e78188a81e0e1e4</span></span>
<span><span class="co">## 6 Northpark_Villa 6af95b5db968bf393e78188a81e0e1e4</span></span>
<span><span class="co">## # ℹ 2,336 more rows</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>If we input Briardale to this hashing function, we will always get the same output. The neighborhoods in this case are called the “keys,” while the outputs are the “hashes.”</p>
<div class="rmdnote">
<p>A hashing function takes an input of variable size and maps it to an output of fixed size. Hashing functions are commonly used in cryptography and databases.</p>
</div>
<p>The <code><a href="https://rlang.r-lib.org/reference/hash.html">rlang::hash()</a></code> function generates a 128-bit hash, which means there are <code>2^128</code> possible hash values. This is great for some applications but doesn’t help with feature hashing of <em>high cardinality</em> variables (variables with many levels). In feature hashing, the number of possible hashes is a hyperparameter and is set by the model developer through computing the modulo of the integer hashes. We can get sixteen possible hash values by using <code>Hash %% 16</code>:</p>
<div class="cell" data-layout-align="center" data-hash="17-encoding-categorical-data_cache/html/unnamed-chunk-12_8a6c33279c21d382b787075cf49af01e">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">ames_hashed</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="co">## first make a smaller hash for integers that R can handle</span></span>
<span>  <span class="fu">mutate</span><span class="op">(</span>Hash <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/strtoi.html">strtoi</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/substr.html">substr</a></span><span class="op">(</span><span class="va">Hash</span>, <span class="fl">26</span>, <span class="fl">32</span><span class="op">)</span>, base <span class="op">=</span> <span class="fl">16L</span><span class="op">)</span>,  </span>
<span>         <span class="co">## now take the modulo</span></span>
<span>         Hash <span class="op">=</span> <span class="va">Hash</span> <span class="op"><a href="https://rdrr.io/r/base/Arithmetic.html">%%</a></span> <span class="fl">16</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu">select</span><span class="op">(</span><span class="va">Neighborhood</span>, <span class="va">Hash</span><span class="op">)</span></span>
<span><span class="co">## # A tibble: 2,342 × 2</span></span>
<span><span class="co">##   Neighborhood     Hash</span></span>
<span><span class="co">##   &lt;fct&gt;           &lt;dbl&gt;</span></span>
<span><span class="co">## 1 North_Ames          9</span></span>
<span><span class="co">## 2 North_Ames          9</span></span>
<span><span class="co">## 3 Briardale           0</span></span>
<span><span class="co">## 4 Briardale           0</span></span>
<span><span class="co">## 5 Northpark_Villa     4</span></span>
<span><span class="co">## 6 Northpark_Villa     4</span></span>
<span><span class="co">## # ℹ 2,336 more rows</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now instead of the 28 neighborhoods in our original data or an incredibly huge number of the original hashes, we have sixteen hash values. This method is very fast and memory efficient, and it can be a good strategy when there are a large number of possible categories.</p>
<div class="rmdnote">
<p>Feature hashing is useful for text data as well as high cardinality categorical data. See Section 6.7 of <span class="citation" data-cites="Hvitfeldt2021">Hvitfeldt and Silge (<a href="references.html#ref-Hvitfeldt2021" role="doc-biblioref">2021</a>)</span> for a case study demonstration with text predictors.</p>
</div>
<p>We can implement feature hashing using a tidymodels recipe step from the <span class="pkg">textrecipes</span> package:</p>
<div class="cell" data-layout-align="center" data-hash="17-encoding-categorical-data_cache/html/unnamed-chunk-13_d807782a18bd7c084fa31712b6244540">
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/tidymodels/textrecipes">textrecipes</a></span><span class="op">)</span></span>
<span><span class="va">ames_hash</span> <span class="op">&lt;-</span> </span>
<span>  <span class="fu"><a href="https://recipes.tidymodels.org/reference/recipe.html">recipe</a></span><span class="op">(</span><span class="va">Sale_Price</span> <span class="op">~</span> <span class="va">Neighborhood</span> <span class="op">+</span> <span class="va">Gr_Liv_Area</span> <span class="op">+</span> <span class="va">Year_Built</span> <span class="op">+</span> <span class="va">Bldg_Type</span> <span class="op">+</span> </span>
<span>           <span class="va">Latitude</span> <span class="op">+</span> <span class="va">Longitude</span>, data <span class="op">=</span> <span class="va">ames_train</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://recipes.tidymodels.org/reference/step_log.html">step_log</a></span><span class="op">(</span><span class="va">Gr_Liv_Area</span>, base <span class="op">=</span> <span class="fl">10</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://textrecipes.tidymodels.org/reference/step_dummy_hash.html">step_dummy_hash</a></span><span class="op">(</span><span class="va">Neighborhood</span>, signed <span class="op">=</span> <span class="cn">FALSE</span>, num_terms <span class="op">=</span> <span class="fl">16L</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://recipes.tidymodels.org/reference/step_dummy.html">step_dummy</a></span><span class="op">(</span><span class="fu"><a href="https://recipes.tidymodels.org/reference/has_role.html">all_nominal_predictors</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://recipes.tidymodels.org/reference/step_interact.html">step_interact</a></span><span class="op">(</span> <span class="op">~</span> <span class="va">Gr_Liv_Area</span><span class="op">:</span><span class="fu">starts_with</span><span class="op">(</span><span class="st">"Bldg_Type_"</span><span class="op">)</span> <span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://recipes.tidymodels.org/reference/step_ns.html">step_ns</a></span><span class="op">(</span><span class="va">Latitude</span>, <span class="va">Longitude</span>, deg_free <span class="op">=</span> <span class="fl">20</span><span class="op">)</span></span>
<span></span>
<span><span class="va">ames_hash</span></span>
<span><span class="co">## </span></span>
<span><span class="co">## ── Recipe ───────────────────────────────────────────────────────────────────────────</span></span>
<span><span class="co">## </span></span>
<span><span class="co">## ── Inputs</span></span>
<span><span class="co">## Number of variables by role</span></span>
<span><span class="co">## outcome:   1</span></span>
<span><span class="co">## predictor: 6</span></span>
<span><span class="co">## </span></span>
<span><span class="co">## ── Operations</span></span>
<span><span class="co">## • Log transformation on: Gr_Liv_Area</span></span>
<span><span class="co">## • Feature hashing with: Neighborhood</span></span>
<span><span class="co">## • Dummy variables from: all_nominal_predictors()</span></span>
<span><span class="co">## • Interactions with: Gr_Liv_Area:starts_with("Bldg_Type_")</span></span>
<span><span class="co">## • Natural splines on: Latitude, Longitude</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Feature hashing is fast and efficient but has a few downsides. For example, different category values often map to the same hash value. This is called a <em>collision</em> or <em>aliasing</em>. How often did this happen with our neighborhoods in Ames? <a href="#tbl-encoding-hash">Table&nbsp;<span>17.3</span></a> presents the distribution of number of neighborhoods per hash value.</p>
<div class="cell" data-layout-align="center" data-hash="17-encoding-categorical-data_cache/html/tbl-encoding-hash_816599df24f33dafb9d6e1d090ba76ad">
<pre><code>## 'as(&lt;dgTMatrix&gt;, "dgCMatrix")' is deprecated.
## Use 'as(., "CsparseMatrix")' instead.
## See help("Deprecated") and help("Matrix-deprecated").</code></pre>
<div class="cell-output-display">
<div id="tbl-encoding-hash" class="anchored">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Table&nbsp;17.3: The number of hash features at each number of neighborhoods.</caption>
<thead><tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Number of neighborhoods within a hash feature</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Number of occurrences</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;">7</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="even">
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="odd">
<td style="text-align: right;">4</td>
<td style="text-align: right;">1</td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
<p>The number of neighborhoods mapped to each hash value varies between zero and four. All of the hash values greater than one are examples of hash collisions.</p>
<p>What are some things to consider when using feature hashing?</p>
<ul>
<li><p>Feature hashing is not directly interpretable because hash functions cannot be reversed. We can’t determine what the input category levels were from the hash value, or if a collision occurred.</p></li>
<li><p>The number of hash values is a <em>tuning parameter</em> of this preprocessing technique, and you should try several values to determine what is best for your particular modeling approach. A lower number of hash values results in more collisions, but a high number may not be an improvement over your original high cardinality variable.</p></li>
<li><p>Feature hashing can handle new category levels at prediction time, since it does not rely on pre-determined dummy variables.</p></li>
<li><p>You can reduce hash collisions with a <em>signed</em> hash by using <code>signed = TRUE</code>. This expands the values from only 1 to either +1 or -1, depending on the sign of the hash.</p></li>
</ul>
<div class="rmdwarn">
<p>It is likely that some hash columns will contain all zeros, as we see in this example. We recommend a zero-variance filter via <code><a href="https://recipes.tidymodels.org/reference/step_zv.html">step_zv()</a></code> to filter out such columns.</p>
</div>
</section><section id="more-encoding-options" class="level2" data-number="17.5"><h2 data-number="17.5" class="anchored" data-anchor-id="more-encoding-options">
<span class="header-section-number">17.5</span> More Encoding Options</h2>
<p>Even more options are available for transforming factors to a numeric representation.</p>
<p>We can build a full set of <em>entity embeddings</em> <span class="citation" data-cites="Guo2016">(<a href="references.html#ref-Guo2016" role="doc-biblioref">Guo and Berkhahn 2016</a>)</span> to transform a categorical variable with many levels to a set of lower-dimensional vectors. This approach is best suited to a nominal variable with many category levels, many more than the example we’ve used with neighborhoods in Ames.</p>
<div class="rmdnote">
<p>The idea of entity embeddings comes from the methods used to create word embeddings from text data. See Chapter 5 of <span class="citation" data-cites="Hvitfeldt2021">Hvitfeldt and Silge (<a href="references.html#ref-Hvitfeldt2021" role="doc-biblioref">2021</a>)</span> for more on word embeddings.</p>
</div>
<p>Embeddings for a categorical variable can be learned via a TensorFlow neural network with the <code><a href="https://embed.tidymodels.org/reference/step_embed.html">step_embed()</a></code> function in <span class="pkg">embed</span>. We can use the outcome alone or optionally the outcome plus a set of additional predictors. Like in feature hashing, the number of new encoding columns to create is a hyperparameter of the feature engineering. We also must make decisions about the neural network structure (the number of hidden units) and how to fit the neural network (how many epochs to train, how much of the data to use for validation in measuring metrics).</p>
<p>Yet one more option available for dealing with a binary outcome is to transform a set of category levels based on their association with the binary outcome. This <em>weight of evidence</em> (WoE) transformation <span class="citation" data-cites="Good1985">(<a href="references.html#ref-Good1985" role="doc-biblioref">Good 1985</a>)</span> uses the logarithm of the “Bayes factor” (the ratio of the posterior odds to the prior odds) and creates a dictionary mapping each category level to a WoE value. WoE encodings can be determined with the <code><a href="https://embed.tidymodels.org/reference/step_woe.html">step_woe()</a></code> function in <span class="pkg">embed</span>.</p>
</section><section id="sec-categorical-summary" class="level2" data-number="17.6"><h2 data-number="17.6" class="anchored" data-anchor-id="sec-categorical-summary">
<span class="header-section-number">17.6</span> Chapter Summary</h2>
<p>In this chapter, you learned about using preprocessing recipes for encoding categorical predictors. The most straightforward option for transforming a categorical variable to a numeric representation is to create dummy variables from the levels, but this option does not work well when you have a variable with high cardinality (too many levels) or when you may see novel values at prediction time (new levels). One option in such a situation is to create <em>effect encodings</em>, a supervised encoding method that uses the outcome. Effect encodings can be learned with or without pooling the categories. Another option uses a <em>hashing</em> function to map category levels to a new, smaller set of dummy variables. Feature hashing is fast and has a low-memory footprint. Other options include entity embeddings (learned via a neural network) and weight of evidence transformation.</p>
<p>Most model algorithms require some kind of transformation or encoding of this type for categorical variables. A minority of models, including those based on trees and rules, can handle categorical variables natively and do not require such encodings.</p>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-Good1985" class="csl-entry" role="listitem">
Good, I. J. 1985. <span>“Weight of Evidence: A Brief Survey.”</span> <em>Bayesian Statistics</em> 2: 249–70.
</div>
<div id="ref-Guo2016" class="csl-entry" role="listitem">
Guo, Cheng, and Felix Berkhahn. 2016. <span>“Entity Embeddings of Categorical Variables.”</span> <a href="http://arxiv.org/abs/1604.06737">http://arxiv.org/abs/1604.06737</a>.
</div>
<div id="ref-Hvitfeldt2021" class="csl-entry" role="listitem">
Hvitfeldt, E., and J. Silge. 2021. <em>Supervised Machine Learning for Text Analysis in r</em>. A Chapman &amp; Hall Book. CRC Press. <a href="https://smltar.com/">https://smltar.com/</a>.
</div>
<div id="ref-fes" class="csl-entry" role="listitem">
Kuhn, M, and K Johnson. 2020. <em>Feature Engineering and Selection: A Practical Approach for Predictive Models</em>. CRC Press.
</div>
<div id="ref-MicciBarreca2001" class="csl-entry" role="listitem">
Micci-Barreca, Daniele. 2001. <span>“A Preprocessing Scheme for High-Cardinality Categorical Attributes in Classification and Prediction Problems.”</span> <em>SIGKDD Explor. Newsl.</em> 3 (1): 27–32. <a href="https://doi.org/10.1145/507533.507538">https://doi.org/10.1145/507533.507538</a>.
</div>
<div id="ref-weinberger2009feature" class="csl-entry" role="listitem">
Weinberger, K, A Dasgupta, J Langford, A Smola, and J Attenberg. 2009. <span>“Feature Hashing for Large Scale Multitask Learning.”</span> In <em>Proceedings of the 26th Annual International Conference on Machine Learning</em>, 1113–20. ACM.
</div>
<div id="ref-Zumel2019" class="csl-entry" role="listitem">
Zumel, Nina, and John Mount. 2019. <span>“Vtreat: A Data.frame Processor for Predictive Modeling.”</span> <a href="http://arxiv.org/abs/1611.09477">http://arxiv.org/abs/1611.09477</a>.
</div>
</div>
</section><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><hr>
<ol>
<li id="fn1"><p>This is in contrast to statistical modeling in Python, where categorical variables are often directly represented by integers alone, such as <code>0, 1, 2</code> representing red, blue, and green.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol></section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./16-dimensionality-reduction.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Dimensionality Reduction</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./18-explaining-models-and-predictions.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Explaining Models and Predictions</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">Modelado Ordenado con R fue escrito por Max Kuhn, y Julia Silge.</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">Este libro fue creado usando <a href="https://quarto.org/">Quarto</a>.</div>
  </div>
</footer>


</body></html>